### ISSUE TITLE
Segfault crash when running the server

### ISSUE THREAD

**Issue by tesYolan** [singnet/opencog-services#47]
##### **Opencog service** 

Ghost
##### **Brief description**
Calling the Ghost service with sync/async client segfaults without any meaningful feedback. 

on fault (core dumped)

##### **Output logs**
```
Server listening on 0.0.0.0:7032
Module /usr/local/lib/opencog/libattention.so loaded.
Agent: opencog::AFImportanceDiffusionAgent loaded.
Agent: opencog::WAImportanceDiffusionAgent loaded.
Agent: opencog::AFRentCollectionAgent loaded.
Agent: opencog::WARentCollectionAgent loaded.
WARNING: (opencog nlp): `get-line' imported from both (ice-9 textual-ports) and (rnrs io ports)
Segmentation fault (core dumped)
```

##### **How to reproduce the error**
Pull https://github.com/singnet/opencog-services/pull/46 and build it with 
```
git clone https://github.com/singnet/opencog-services.git
docker build -t opencog_services_basic  --file basic-dockerfile .
sudo docker build -t opencog_services --file Dockerfile .

# exec into the containers
./bin/server

# on another exec into the containers i.e docker exec -it container_name /bin/bash
./bin/client sync Ghost start_session https://raw.githubusercontent.com/Ophien/rulefile
```

##### **Suggest a Fix**

There seems to be similar albeit different issue at: https://github.com/opencog/opencog/issues/3484

But that seems to have been resolved. 

I have tried few iterations going through at https://github.com/singnet/opencog-services/blob/4cfa9f1daf91dec195c9ff93045285528bc9e9a6/src/guileSession.cc#L151

and it seems something is weird going on as it seems it can't handle empty lines. But I don't understand how to solve it. 

##### **Container and Operating System**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by leungmanhin** [comment]
Though I don't fully understanding the issue yet, but if it's related to exiting Guile while Ghost is running (as in opencog/opencog#3484), you may try doing `(ghost-halt)` first

**Comment by tesYolan** [comment]
Interspersed print statement revels the following properties: 
```
3215: Received command: (use-modules (opencog nlp sureal) (opencog nlp microplanning))
3215: Response:
3215: Response: NOTHING
3215: Received command: (use-modules (opencog nlp aiml) (opencog openpsi))
3215: Response:
3215: Response: NOTHING
3215: Received command: (use-modules (opencog ghost))
3215: Response:
3215: Response: NOTHING
3215: Received command: (use-modules (opencog ghost procedures))
3215: Response:
3215: Response: NOTHING
3215: Received command: (use-modules (opencog cogserver))
3215: Response:
3215: Response: NOTHING
3215: Received command:
Command is empty
3215: Response:
3215: Response: NOTHING
Segmentation fault (core dumped)
root@416299b33a0d:/opt/singnet/opencog-services# 3191: Received command:
Command is empty
3191: Response:
3191: Response: NOTHING
```

I don't particularly understand why the loop continues even after there is no command to be read. Both `continue` and `exit` have undesirable behavior. In the case of continue after empty command, it gets into an infinity loop, and with exit it still crashes.

**Comment by tesYolan** [comment]
Found the culprit: 
https://github.com/singnet/opencog-services/blob/master/src/cpp-services/Ghost.cc#L76

It reads getenv variable to read relex server address, if it doesn't find it it segfaults. 

It should resolve to default `127.0.0.1` as it is placed in relex-utiils.scm. 

Works now.

**Comment by tesYolan** [comment]
Will fix the undefined reference once  I have the rest of the system up.
